version: '3.8'
services:
  spring-boot-app:
    build: ./spring
    ports:
      - "8080:8080"
    depends_on:
      - db

  angular-app:
    build: ./angular
    ports:
      - "4200:4200"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: farid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
